### ISSUE TITLE
Some blocks failed

### ISSUE THREAD

**Issue by ludmildev** [vsys-host/tron-shkeeper#3]
Image:         vsyshost/tron-shkeeper:1.0.20

ERROR <ThreadPoolExecutor-1_0 Thread>: Block 1298: Failed to scan:                              │
│ Traceback (most recent call last):                                                                                        │
│   File "/app/app/block_scanner.py", line 164, in scan                                                                     │
│     block = self.download_block(block_num)                                                                                │
│   File "/app/app/block_scanner.py", line 148, in download_block                                                           │
│     block = ConnectionManager.client().get_block(n)                                                                       │
│   File "/usr/local/lib/python3.8/site-packages/tronpy/tron.py", line 662, in get_block                                    │
│     raise BlockNotFound                                                                                                   │
│ tronpy.exceptions.BlockNotFound
INFO <Block Scanner Thread>: Some blocks failed, retrying chunk 1297 - 1298

**Comment by PiotrBaczkowski96** [comment]
I have same issue

**Comment by PiotrBaczkowski96** [comment]
@ludmildev did you manage to fix it somehow editing databases with last block?

**Comment by ludmildev** [comment]
Yep, didnt help...

**Comment by PiotrBaczkowski96** [comment]
@ludmildev downgrading image also doesnt help, let me know if you find solution

**Comment by PiotrBaczkowski96** [comment]
@ludmildev 
You need to get into bash in your tron full node
kubectl get pod -n shkeeper

kubectl exec -it  ${tron-pod-name} -n shkeeper bash

then inside pod

cd data 
apt-get update
apt-get install sqlite3 
then 
sqlite3 ./database.db

//inside sqlite3 execute following command(you can replace 67719770 to any block you preffer)

update settings set value =     '67719770' where name = 'last_seen_block_num';
